# Generated by Django 2.0.4 on 2018-04-19 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('summary', models.TextField(max_length=500)),
                ('link', models.URLField()),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('last_modified_tag', models.CharField(default=None, max_length=50, null=True)),
                ('last_modified_value', models.TextField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.SourceRSS'),
        ),
        migrations.AddField(
            model_name='comments',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.NewsItem'),
        ),
    ]
